public class Cat1{
    public String name;
    public Integer size;
    public Cat1(String n,Integer s){//this is one of the constructor
        name=n;
        size=s;    
    }
    public void display(){
        System.debug('Name of my cat '+name);
        System.debug('Size of my cat '+size);
    }
}
/*public class Cat{
    public String name;
    public Integer size;
    public Cat(String n,Integer s){//this is one of the constructor
        name=n;
        size=s;    
    }
    public void display(){
        System.debug('Name of my cat '+name);
        System.debug('Size of my cat '+size);
    }
}*/