/*public class WhileLoopExample {
    public static void loopwhileDemo(){
         integer i=1;
       /* while(i<10){
            System.debug(i);
            i++;
        }*/
       /* do{
            System.debug(i);
            i++;
        }While(i<10); //do{}while至少会运行第一次，然后再判断条件对不对？？？？       
    }
} */ //调用WhileLoopExample.loopwhileDemo();

/*public class WhileLoopExample{
    public static void ForLoopDemon(){
        for(integer i=1;i<=10;i++){
            System.debug(i);
        }//调用WhileLoopExample.ForLoopDemon();
    }
}*/
//Assignment on loops
/*public class WhileLoopExample{
    public static void ForLoopExample1(){
        for(integer i=1;i<=16;i=i+3){
            System.debug(i);
        }
    }
}*/
/*public class WhileLoopExample{
    public static void ForLoopExample2(){
        for(integer i=5;i<=20;i=i+5){
            System.debug(i);
        }
    }
}*/
public class WhileLoopExample{
    public static void ForLoopExample3(){
        for(integer i=2;i<=10;i=i+2){
            System.debug(i);
        }
    }
}